.TH "display-fbdev" 7 GGI
.SH NAME
display-fbdev \- Display using Linux kernel framebuffer devices
.SH SYNOPSIS
 \fBdisplay-fbdev\fR : -noinput -nokbd -nomouse -novt -physz=\fIsizex\fR,\fIsizey\fR\fIdpi\fR \fIframebuffer\fR 
.SH DESCRIPTION
Uses the Linux \fB/dev/fb*\fR devices to do fullscreen graphics.

When using a regular fbdev driver, \fB/etc/fb.modes\fR  is used to determine the available modes for the device. Driver timings and resolutions can be automatically obtained when running under KGIcon.
.SH OPTIONS
.TP
\fIframebuffer\fR
The filename of the framebuffer target to use.  The default is to get it from the \fBFRAMEBUFFER\fR environment, or the framebuffer associated with the current console if that is unset.
.PP
.TP
-nokbd
Do not open any libraries for keyboard input.
.PP
.TP
-nomouse
Do not open any libraries for mouse input.
.PP
.TP
-noinput
Same as both -nokbd and -nomouse.
.PP
.TP
-novt
Disable virtual console support.
.PP
.TP
-physz=\fIsizex\fR,\fIsizey\fR\fIdpi\fR
This option will provide a physical screen size for applications which  wish to remain resolution independent.   \fIsizex\fR,\fIsizey\fR are the x,y  size of the screen in millimeters, unless the optional \fIdpi\fR string is affixed, in which case, they represent resolution in dots-per-inch.
.PP
.SH FEATURES
.RS
.IP \(bu 4
DirectBuffer always available.
.IP \(bu 4
Accelerated when using KGIcon or matroxfb.
.IP \(bu 4
Multiple frames
.IP \(bu 4
Panning
.RE
.SH SEE ALSO
.RS
.IP \(bu 4
\fBfb.modes\fR (5)
.RE

