.TH "display-aa" 7 GGI
.SH NAME
display-aa \- Display using AAlib
.SH SYNOPSIS
\fBdisplay-aalib\fR
.SH DESCRIPTION
Uses the AA-lib, an ASCII art library, for output and input.
.SH ENVIRONMENT VARIABLES
AA-lib options may be specified using the the \fBAA_OPTS\fR variable.
.SH FEATURES
.RS
.IP \(bu 4
DirectBuffer always available
.IP \(bu 4
Unaccelerated
.IP \(bu 4
Currently, only supports 8-bit palettized modes
.RE

