.TH "display-vnc" 7 "2006-09-10" "libggi-current" GGI
.SH NAME
\fBdisplay-vnc\fR : Display on vnc client over a network
.SH SYNOPSIS
.nb
.nf
display-vnc: [-client=<host>] [-copyrect=no|always] [-display=<dpy>]
             [-hextile=no] [-passwd=<pass>] [-title=<title>] [-zlib=<level>]
             [-zrle=<level>]
.fi

.SH DESCRIPTION
Provides a linear framebuffer in main memory. A vnc client that
connects gets to see a copy of this framebuffer. The protocol
used is the remote framebuffer protocol, or the RFB protocol for
short.

The supported RFB protocol versions are 3.3, 3.7 and 3.8.
.SH OPTIONS
.TP
\f(CW-client=<host>\fR
Make a connection to \fIhost\fR, instead of waiting for clients to
connect. A vnc viewer in listening mode is expected to be found on
\fIhost\fR.

.TP
\f(CW-copyrect=no|always\fR
Controls when the CopyRect encoding is used. Select \fIno\fR to disable
it completely, and \fIalways\fR to enable it when suitable even if there
is support for some other encoding the client has preferred. The default
is to only use the CopyRect encoding if it is the most preferred
encoding available.

.TP
\f(CW-display=<dpy>\fR
The display number clients should connect to. Display number 0 is
equivalent to tcp port 5900.

If the \fI-client\fR option is also given, this is instead the display
number this server connects to, and display number 0 is equivalent
to tcp port 5500 in that case.

.TP
\f(CW-hextile=no\fR
Disables the hextile encoding.

.TP
\f(CW-passwd=<password>\fR
The vnc client has to successfully encrypt a random challenge
with the stated \fIpassword\fR in order to connect. In the
\fIpassword\fR, only the eight first characters and the seven least
significant bits of every character are used in the authentication.

.TP
\f(CW-title=<title>\fR
The \fItitle\fR clients should use on their windows. If this option
is not specified, the default is "GGI on vnc".

.TP
\f(CW-zlib=<level>\fR
Specify the compression level to use for the zlib encoding. 0 for
no compression and 9 for maximum compression. Saying \fIno\fR here
disables the zlib encoding. If the option isn't specified, a default
compromize between speed and compression is selected.

.TP
\f(CW-zrle=<level>\fR
Specify the compression level to use for the ZRLE encoding. 0 for
no compression and 9 for maximum compression. Saying \fIno\fR here
disables the ZRLE encoding. If the option isn't specified, a default
compromize between speed and compression is selected.

.PP
.SH FEATURES
.IP \(bu 4
Raw, CopyRect, Hextile, zlib and ZRLE encodings. The CopyRect encoding
is only used for panning.
.IP \(bu 4
Multiple simultaneous clients.
.IP \(bu 4
DirectBuffer always available, including tidy buffer mode (see
\f(CWggiSetFlags(3)\fR).
.IP \(bu 4
Multiple frames always available.
.IP \(bu 4
Panning always available.
.IP \(bu 4
Unaccelerated.
.PP
.SH BUGS
.IP \(bu 4
Special keys (i.e. shift, escape, etc) needs to be converted.
.PP
