.TH "display-trueemu" 7 GGI
.SH NAME
\fBdisplay-trueemu\fR : Emulate truecolor modes
.SH SYNOPSIS
.nb
display-trueemu : [-parent=<mode>] [-dither=<dither>]
                  [-model=<model>] <target-spec>
.fi
.SH DESCRIPTION
Emulates truecolor modes (\fBGT_TRUECOLOR\fR) on another target which can
only do palette modes or truecolor modes of different sizes/depths.
Uses dithering and special palettes to get the highest possible
quality.
.SH OPTIONS
.TP
\fB-parent=<mode>\fR
Force the parent target to use a specific \fBmode\fR, specified as a
standard LibGGI mode string (see \fBlibggi(7)\fR).
.PP
.TP
\fB-dither=<dither>\fR
Specifies the amount of dithering.  Legal values are 0, 2 and 4,
defaulting to 4. When the target is running, \fBCtrl-Alt-d\fR
changes the dithering level.
.PP
.TP
\fB-model=<model>\fR
Color model to use (only when the parent is palettized).  Legal
values are rgb, cube and pastel.  Default depends on the parent
mode. When the target is running, \fBCtrl-Alt-p\fR changes the
current color model.
.PP
.TP
\fBtarget-spec\fR
Specifies the target which to draw on (the \fIparent\fR target).  This
defaults to automatic selection (just like using \fBggiOpen(NULL)\fR
when \fBGGI_DISPLAY\fR is not set).
.PP
.SH FEATURES
.IP \(bu 4
DirectBuffer never supported.
.IP \(bu 4
Unaccelerated.
