.TH "display-aa" 7 "2006-02-22" "libggi-current" GGI
.SH NAME
\fBdisplay-aa\fR : Display using AAlib
.SH SYNOPSIS
.nb
.nf
display-aalib
.fi

.SH DESCRIPTION
Uses the AA-lib, an ASCII art library, for output and input.
.SH ENVIRONMENT VARIABLES
AA-lib options may be specified using the the \fBAAOPTS\fR variable.
.SH FEATURES
.IP \(bu 4
DirectBuffer always available
.IP \(bu 4
Unaccelerated
.IP \(bu 4
Currently, only supports 8-bit palettized modes
.PP
