.TH "display-multi" 7 GGI
.SH NAME
\fBdisplay-multi\fR : Duplicate visual operations onto multiple visuals
.SH SYNOPSIS
.nb
display-multi <:targetspec> ...
.fi
.SH DESCRIPTION
Duplicates all drawing operations onto multiple \fIchild\fR targets, thus
producing identical output on multiple visuals.
.SH OPTIONS
The argument to \fBdisplay-multi\fR is a colon- (\fB:\fR) separated list of
target specs to draw on.  Because target specs can (and often do)
contain colons, they need to be enclosed in parentheses.
.SH FEATURES
.IP \(bu 4
DirectBuffer never supported.
.IP \(bu 4
Unaccelerated.
.PP
