.TH "display-vcsa" 7 GGI
.SH NAME
display-vcsa \- Display using Linux virtual console text device
.SH SYNOPSIS
\fBdisplay-vcsa\fR : -noinput -nokbd -nomouse -shade -ascii -physz=\fIsizex\fR,\fIsizey\fR\fIdpi\fR \fIvcsa device\fR
.SH DESCRIPTION
Uses the Linux \fB/dev/vcsa*\fR devices to render text modes onto the console.
.SH OPTIONS
.TP
-nokbd
Do not open any libraries for keyboard input.
.PP
.TP
-nomouse
Do not open any libraries for mouse input.
.PP
.TP
-noinput
Same as both -nokbd and -nomouse.
.PP
.TP
-shade
The -shade option turns on `shading mode', which changes the color mapping so that it chooses characters which emulate a shading effect. This makes a big improvement if using (some might say abusing :) the vcsa target for graphical purposes.
.PP
.TP
-ascii
The -ascii option limits the color mapping to only using ASCII characters. The default mode uses IBM special characters (the solid block mainly, and others when using -shade).
.PP
.TP
-physz=\fIsizex\fR,\fIsizey\fR\fIdpi\fR
This option will provide a physical screen size for applications which wish to remain resolution independent. \fIsizex\fR,\fIsizey\fR are the x,y size of the screen in millimeters, unless the optional \fIdpi\fR string is affixed, in which case, they represent resolution in dots-per-inch.
.PP
.TP
\fIvcsa device\fR
The filename of the device file, defaulting to \fB/dev/vcsa\fR which draws on the current virtual console.
.PP
.SH FEATURES
.RS
.IP \(bu 4
No DirectBuffer support.
.IP \(bu 4
Unaccelerated.
.RE

