.TH "display-auto" 7 "2004-01-30" "libggi-current" GGI
.SH NAME
\fBdisplay-auto\fR : OS dependent target autodetection
.SH SYNOPSIS
.nb
.nf
display-auto
.fi

.SH DESCRIPTION
It provides OS dependent target autodetection.

It is automatically invoked when you open a default
target with \fBggiOpen()\fR. It unloads itself automatically
before \fBggiOpen()\fR returns back to the application,
successful or not.

It probes several targets. It tries the next
target when the one before is given up.
Before a target is given up, it can even probe
a target with different (target specific) options.
.SH EXAMPLES
Say, you're on a remote session and open a default target.
Say, the X-target is tried first. It fails, because the
shm extension is only locally usable.
So it tries the X-target again, but this time with the
\fB-noshm\fR option. This should work then.

Say, you are on a console, no X available. The X-target
will fail (after some retries). If you are on Linux,
next targets may be fbdev, svgalib, terminfo, aalib, etc.
If you are on FreeBSD, next targets may be vgl and aalib.

Similar counts for all other Operating Systems such as
MacOSX, Open- and NetBSD, Windows, Solaris, etc.
.SH SEE ALSO
\f(CWggiOpen(3)\fR
