.TH "display-sub" 7 GGI
.SH NAME
\fBdisplay-sub\fR : Make a child visual that is a window to the parent
.SH DESCRIPTION
Creates a "child" visual within a "parent". This can be thought of as
a window and the \fBdisplay-sub\fR target is intended for simple windowing
systems.

No textual arguments, since this target can only be used by
applications. \fBargptr\fR must contain the parent visual.

The sub target behaves a bit special with respect to (i.e. abuses the
semantics of :) the \fBggiSetMode(3)\fR call. It uses the "visible"
size for the top left corner position of the window within the visual,
and the "virtual" size for window width and height.  Note, that
moving/resizing the window does \fInot\fR cause any drawing action.  You
have to perform those yourself. All it does for you is providing a
virtual visual within an existing one, which is convenient to allow
for window system canvases to be about any GGI program.
.SH FEATURES
.IP \(bu 4
DirectBuffer not supported.
.IP \(bu 4
Accelerated to the point of the parent. Calls are mapped through
with modified clipping and coordinates.
.PP
