.TH "display-fbdev" 7 GGI
.SH NAME
\fBdisplay-fbdev\fR : Display using Linux kernel framebuffer devices
.SH SYNOPSIS
.nb
display-fbdev: [ [-noinput] | [ [-nokbd] | [-nomouse] ] ] [-novt]
               [-physz=<sizex>,<sizey>[dpi]] [<framebuffer>]
.fi
.SH DESCRIPTION
Uses the Linux \fB/dev/fb*\fR devices to do fullscreen
graphics.
When using a regular fbdev driver, \fB/etc/fb.modes\fR is used to
determine the available modes for the device.  Driver timings and
resolutions can be automatically obtained when running under KGIcon.
.SH OPTIONS
.TP
\fBframebuffer\fR
The filename of the framebuffer target to use.  The default is to
get it from the \fBFRAMEBUFFER\fR environment, or the framebuffer
associated with the current console if that is unset.
.PP
.TP
\fB-nokbd\fR
Do not open any libraries for keyboard input.
.PP
.TP
\fB-nomouse\fR
Do not open any libraries for mouse input.
.PP
.TP
\fB-noinput\fR
Same as both \fB-nokbd\fR and \fB-nomouse\fR.
.PP
.TP
\fB-novt\fR
Disable virtual console support.
.PP
.TP
\fB-physz=<sizex>,<sizey>[dpi]\fR
This option will provide a physical screen size for applications
which wish to remain resolution independent.
\fBsizex\fR,:p:\fBsizey\fR are the x,y size of the screen in
millimeters, unless the optional \fBdpi\fR string is affixed, in
which case, they represent resolution in dots-per-inch.
.PP
.SH FEATURES
.IP \(bu 4
DirectBuffer always available.
.IP \(bu 4
Accelerated when using KGIcon or matroxfb.
.IP \(bu 4
Multiple frames.
.IP \(bu 4
Panning.
.SH SEE ALSO
\fBfb.modes(5)\fR
