.TH "display-trueemu" 7 "2003-04-02" "libggi-current" GGI
.SH NAME
\fBdisplay-trueemu\fR : Emulate truecolor modes
.SH SYNOPSIS
.nb
.nf
display-trueemu : [-parent=<mode>] [-dither=<dither>]
                  [-model=<model>] <target-spec>
.fi

.SH DESCRIPTION
Emulates truecolor modes (\fBGT_TRUECOLOR\fR) on another target which can
only do palette modes or truecolor modes of different sizes/depths.
Uses dithering and special palettes to get the highest possible
quality.
.SH OPTIONS
.TP
\f(CW-parent=<mode>\fR
Force the parent target to use a specific \fImode\fR, specified as a
standard LibGGI mode string (see \f(CWlibggi(7)\fR).

.TP
\f(CW-dither=<dither>\fR
Specifies the amount of dithering.  Legal values are 0, 2 and 4,
defaulting to 4. When the target is running, \f(CWCtrl-Alt-d\fR
changes the dithering level.

.TP
\f(CW-model=<model>\fR
Color model to use (only when the parent is palettized).  Legal
values are rgb, cube and pastel.  Default depends on the parent
mode. When the target is running, \f(CWCtrl-Alt-p\fR changes the
current color model.

.TP
\fItarget-spec\fR
Specifies the target which to draw on (the \fIparent\fR target).  This
defaults to automatic selection (just like using \f(CWggiOpen(NULL)\fR
when \fBGGI_DISPLAY\fR is not set).

.PP
.SH FEATURES
.IP \(bu 4
DirectBuffer never supported.
.IP \(bu 4
Unaccelerated.
.PP
