.TH "display-vnc" 7 "2006-08-20" "libggi-current" GGI
.SH NAME
\fBdisplay-vnc\fR : Display on vnc clinet over a network
.SH SYNOPSIS
.nb
.nf
display-vnc: [-display=<dpy>]
.fi

.SH DESCRIPTION
Provides a linear framebuffer in main memory. A vnc client that
connects gets to see a copy of this framebuffer. The protocol
used is the remote framebuffer protocol, or the RFB protocol for
short.

The supported RFB protocol versions are 3.3, 3.7 and 3.8.
.SH OPTIONS
.TP
\f(CW-display=<dpy>\fR
The display number clients should connect to. Display number 0 is
equivalent of tcp port 5900.

.PP
.SH FEATURES
.IP \(bu 4
Unaccelerated.
.PP
.SH BUGS
.IP \(bu 4
Clients are not authenticated.
.IP \(bu 4
The raw encoding is the only supported encoding.
.IP \(bu 4
Always updates the whole framebuffer, no matter what.
.IP \(bu 4
Special keys (i.e. shift, escape, etc) needs to be converted.
.IP \(bu 4
A DoS attack is easy as an existing client is disconnected as soon
as a new one connects.
.IP \(bu 4
Palettized modes don't appear to work...
.PP
