.TH "display-tele" 7 "2003-04-02" "libggi-current" GGI
.SH NAME
\fBdisplay-tele\fR : Forwards the display over a network
.SH SYNOPSIS
.nb
.nf
display-tele: <host>[:port]
.fi

.SH DESCRIPTION
The tele target forwards the display over a network via TCP to a
remote host.

A \fBggiteleserver(1)\fR must be running on the remote host where the final
display resides. A normal GGI applications will then use the tele
target to forward all graphic operations to the machine running the
teleserver.
.SH OPTIONS
The first argument to \fBdisplay-tele\fR is the hostname to connect to
(the display server). The second optional argument is the port on
which the server is listening. The default port is 27780.
.SH FEATURES
.IP \(bu 4
DirectBuffer never supported.
.IP \(bu 4
Accelerated if the remote display is.
.PP
.SH SEE ALSO
\fBggiteleserver(1)\fR
