.TH "display-glide" 7 GGI
.SH NAME
display-glide \- Display using Glide library
.SH SYNOPSIS
\fBdisplay-glide\fR : \fIcard\fR
.SH DESCRIPTION
Uses the Glide library to display fullscreen on a 3DFX graphics card.
.SH OPTIONS
The 3DFX card to use can be optionally specified as a cardinal number minus one. (e.g. 0 means the first card, 1 the second, etc.)
.SH ENVIRONMENT VARIABLES
.TP
\fBGGI_GLIDE_MAXFREQ\fR
specifies the maximum update frequency your monitor can handle (in Hz). Default is 70Hz.
.PP
.TP
\fBGGI_GLIDE_MAXHFREQ\fR
specifies the maximum horizontal frequency your monitor can handle (in kHz). Default is 48kHz.
.PP
.TP
\fBGGI_GLIDE_HALTONSWITCH\fR
if this is set applications will be halted on console switchaway. The default is to continue running.
.PP
.SH FEATURES
.RS
.IP \(bu 4
DirectBuffer never available.
.IP \(bu 4
Accelerated, one of the fastest targets when it comes to drawing-primitives.
.IP \(bu 4
Multiple frames.
.RE

