.TH "ggiCopyBox" 3 "2005-02-26" "libggi-current" GGI
.SH NAME
\fBggiCopyBox\fR : Copy a rectangular area
.SH SYNOPSIS
.nb
.nf
#include <ggi/ggi.h>

int ggiCopyBox(ggi_visual_t vis, int x, int y, int w, int h, int nx ,int ny);
.fi

.SH DESCRIPTION
This is a area-to-area-blit, all in the same visual. Copy the box
described by \fIx\fR, \fIy\fR, \fIw\fR, \fIh\fR to the new location
\fInx\fR, \fIny\fR.  This automatically takes care of overlaps and
optimizes for the given visual (e.g. uses HW-accel or intermediate
buffers as appropriate).

\fBggiCopyBox\fR will transfer an area between frames when the read frame
is not the same as the write frame.
.SH RETURN VALUE
\fB0\fR for OK, otherwise an \fBggi-error(3)\fR code.
.SH SEE ALSO
\fBggiCrossBlit(3)\fR
