.TH "ggiDrawPixel" 3 GGI
.SH NAME
ggiDrawPixel, ggiPutPixel, ggiGetPixel \- Draw, put, and get a single pixel from a visual
.SH SYNOPSIS
\fB#include <ggi/ggi.h>\fR

int \fBggiDrawPixel\fR( ggi_visual_t \fIvis\fR, int \fIx\fR, int \fIy\fR );

int \fBggiPutPixel\fR( ggi_visual_t \fIvis\fR, int \fIx\fR, int \fIy\fR, ggi_pixel \fIcol\fR );

int \fBggiGetPixel\fR( ggi_visual_t \fIvis\fR, int \fIx\fR, int \fIy\fR, ggi_pixel *\fIcol\fR );
.SH DESCRIPTION
Draw, put, or get a single pixelvalue at (\fIx\fR,\fIy\fR).
.SH RETURN VALUE
All three functions return \fB0\fR to indicate success.

