.TH "ggiDrawVLine" 3 GGI
.SH NAME
ggiDrawVLine, ggiPutVLine, ggiGetVLine \- Draw, put, and get a vertical line from a visual
.SH SYNOPSIS
\fB#include <ggi/ggi.h>\fR

int \fBggiDrawVLine\fR( ggi_visual_t \fIvis\fR,  int \fIx\fR,  int \fIy\fR,  int \fIh\fR );

int \fBggiPutVLine\fR( ggi_visual_t \fIvis\fR,  int \fIx\fR,  int \fIy\fR,  int \fIh\fR,  void *\fIbuf\fR );

int \fBggiGetVLine\fR( ggi_visual_t \fIvis\fR,  int \fIx\fR,  int \fIy\fR,  int \fIh\fR,  void *\fIbuf\fR );
.SH DESCRIPTION
Draw, put, or get a vertical line from (\fIx\fR,\fIy\fR), extending \fIh\fR pixels in the positive y direction (normally down). The width of the line is one pixel.

The *\fIbuf\fR parameter in Get/Put functions points to a buffer from which the pixels will be read, or to which they will be written (it must be correctly allocated), depending on the case. See \fBggiPackColors\fR and \fBggiUnmapPixels\fR functions for more on how to deal with pixels.
.SH RETURN VALUE
All three functions return \fB0\fR to indicate success.
.SH SEE ALSO
\fBggiDrawHLine\fR (3), \fBggiDrawBox\fR (3), \fBggiDrawLine\fR (3), \fBggiMapColor\fR (3), \fBggi_pixelformat\fR (3) 
