.TH "ggiDrawBox" 3 "2007-12-17" "libggi-current" GGI
.SH NAME
\fBggiDrawBox\fR, \fBggiPutBox\fR, \fBggiGetBox\fR : Draw, put, and get a rectangle from a visual
.SH SYNOPSIS
.nb
.nf
#include <ggi/ggi.h>

int ggiDrawBox(ggi_visual_t vis, int x, int y, int w, int h);

int ggiPutBox(ggi_visual_t vis, int x, int y, int w, int h, const void *buf);

int ggiGetBox(ggi_visual_t vis, int x, int y, int w, int h, void *buf);
.fi

.SH DESCRIPTION
Draw, put, or get a rectangle at (\fIx\fR, \fIy\fR), extending \fIw\fR
pixels in the positive x direction and \fIh\fR pixels in the positive y
direction.

The \fIbuf\fR parameter in Get/Put functions points to a buffer from
which the pixels will be read, or to which they will be written (it
must be correctly allocated), respectively. See
\f(CWggiPackColors(3)\fR and \f(CWggiUnmapPixel(3)\fR functions for
details on how to deal with pixels.
.SH RETURN VALUE
All three functions return \fB0\fR to indicate success.
.SH SEE ALSO
\f(CWggiDrawHLine(3)\fR, \f(CWggiDrawLine(3)\fR, \f(CWggiDrawVLine(3)\fR,
\f(CWggiMapColor(3)\fR, \f(CWggi_pixelformat(3)\fR
