.TH "ggiDrawHLine" 3 "2004-11-25" "libggi-current" GGI
.SH NAME
\fBggiDrawHLine\fR, \fBggiPutHLine\fR, \fBggiGetHLine\fR : Draw, put, and get a horizontal line from a visual
.SH SYNOPSIS
.nb
.nf
#include <ggi/ggi.h>

int ggiDrawHLine(ggi_visual_t vis, int x, int y, int w);

int ggiPutHLine(ggi_visual_t vis, int x, int y, int w, void *buf);

int ggiGetHLine(ggi_visual_t vis, int x, int y, int w, void *buf);
.fi

.SH DESCRIPTION
Draw, put, or get a horizontal line from (\fIx\fR, \fIy\fR), extending
\fIw\fR pixels in the positive x direction (normally right).  The
height is one pixel.

The \fIbuf\fR parameter in Get/Put functions points to a buffer from
which the pixels will be read, or to which they will be written (it
must be correctly allocated), respectively. See
\fBggiPackColors(3)\fR and \fBggiUnmapPixel(3)\fR functions for
details on how to deal with pixels.
.SH RETURN VALUE
All three functions return \fB0\fR to indicate success.
.SH SEE ALSO
\fBggiDrawBox(3)\fR, \fBggiDrawLine(3)\fR, \fBggiDrawVLine(3)\fR,
\fBggiMapColor(3)\fR, \fBggi_pixelformat(3)\fR
