.TH "ggiDrawVLine" 3 "2003-04-02 06:39:16" "ggi-current" GGI
.SH NAME
\fBggiDrawVLine\fR, \fBggiPutVLine\fR, \fBggiGetVLine\fR : Draw, put, and get a vertical line from a visual
.SH SYNOPSIS
.nb
.nf
#include <ggi/ggi.h>

int ggiDrawVLine(ggi_visual_t vis, int x, int y, int h);

int ggiPutVLine(ggi_visual_t vis, int x, int y, int h, void *buf);

int ggiGetVLine(ggi_visual_t vis, int x, int y, int h, void *buf);
.fi
.SH DESCRIPTION
Draw, put, or get a vertical line from (\fBx\fR, \fBy\fR), extending
\fBh\fR pixels in the positive y direction (normally down). The width
of the line is one pixel.

The \fBbuf\fR parameter in Get/Put functions points to a buffer from
which the pixels will be read, or to which they will be written (it
must be correctly allocated), respectively. See
\fBggiPackColors(3)\fR and \fBggiUnmapPixel(3)\fR functions for
details on how to deal with pixels.
.SH RETURN VALUE
All three functions return \fB0\fR to indicate success.
.SH SEE ALSO
\fBggiDrawHLine(3)\fR, \fBggiDrawBox(3)\fR, \fBggiDrawLine(3)\fR,
\fBggiMapColor(3)\fR, \fBggi_pixelformat(3)\fR
