.TH "ggiDrawLine" 3 GGI
.SH NAME
ggiDrawLine \- Draw a line on a visual
.SH SYNOPSIS
\fB#include <ggi/ggi.h>\fR

int \fBggiDrawLine\fR( ggi_visual_t \fIvis\fR,  int \fIx\fR,  int \fIy\fR,  int \fIxe\fR,  int \fIye\fR );
.SH DESCRIPTION
Draws any line, using the current foreground color, from (\fIx\fR,\fIy\fR) to (\fIxe\fR,\fIye\fR). The line is exact; the pixel set is no more than 0.5 pixels off the place it should be.
.SH RETURN VALUE
This function returns \fB0\fR to indicate success.
.SH SEE ALSO
\fBggiDrawHLine\fR (3), \fBggiDrawVLine\fR (3)  
