.TH "ggiEventSend" 3 GGI
.SH NAME
\fBggiEventSend\fR : Send commands and events to a LibGGI visual
.SH SYNOPSIS
.nb
#include <ggi/ggi.h>

int ggiEventSend(ggi_visual_t vis, gii_event *ev);
.fi
.SH DESCRIPTION
\fBggiEventSend\fR injects an event into the queue.
.SH CONTROLLING VT SWITCHING BEHAVIOR
If an application wants to continue running after its VT is switched
away, it should make a call \fBggiEventSend\fR to the visual with an
\fBevCommand\fR event with code \fBGGICMD_NOHALT_ON_UNMAP\fR.  To disable this
behavior, use a command event with code \fBGGICMD_HALT_ON_UNMAP\fR.  The
latter is the default.
.SH SEE ALSO
\fBggiEventPoll(3)\fR, \fBgiiEventSend(3)\fR
