.TH "ggiFlush" 3 GGI
.SH NAME
ggiFlush, ggiFlushRegion \- Flush pending output
.SH SYNOPSIS
\fB#include <ggi/ggi.h>\fR

int \fBggiFlush\fR( ggi_visual_t \fIvis\fR );

int \fBggiFlushRegion\fR( ggi_visual_t \fIvis\fR, int \fIx\fR, int \fIy\fR, int \fIw\fR, int \fIh\fR );
.SH DESCRIPTION
\fBggiFlush\fR waits for the visual to finish pending accelerator commands, and in some targets, it refreshes the framebuffer.

\fBggiFlushRegion\fR performs the flush function only in the specified region if it would improve performance.

These functions are not needed if the visual is in synchronous mode.
.SH RETURN VALUE
No meaningful return value.
.SH SEE ALSO
\fBggiSetFlags\fR (3) 
