.TH "ggiFillscreen" 3 GGI
.SH NAME
ggiFillscreen \- Fills the entire virtual screen
.SH SYNOPSIS
\fB#include <ggi/ggi.h>\fR

int \fBggiFillscreen\fR( ggi_visual_t \fIvis\fR );
.SH DESCRIPTION
Fills the current clipping rectangle (usually the entire virtual screen) with the current foreground color.  It may be more efficient than the corresponding call to \fBggiDrawBox\fR.
.SH RETURN VALUE
This function returns \fB0\fR to indicate success.

