.TH "ggiFillscreen" 3 "2004-10-15" "libggi-current" GGI
.SH NAME
\fBggiFillscreen\fR : Fill the entire virtual screen
.SH SYNOPSIS
.nb
.nf
#include <ggi/ggi.h>

int ggiFillscreen(ggi_visual_t vis);
.fi

.SH DESCRIPTION
Fills the current clipping rectangle (usually the entire virtual
screen) with the current foreground color.  It may be more efficient
than the corresponding call to \fBggiDrawBox(3)\fR. To set a clipping
rectangle, see \fBggiSetGCClipping(3)\fR.
.SH RETURN VALUE
This function returns \fB0\fR to indicate success.
