.TH "ggiGetPixelFormat" 3 "2007-05-06" "libggi-current" GGI
.SH NAME
\fBggiGetPixelFormat\fR : Get a structure describing the format of a pixelvalue from a visual
.SH SYNOPSIS
.nb
.nf
#include <ggi/ggi.h>

const ggi_pixelformat *ggiGetPixelFormat(ggi_visual_t vis);
.fi

.SH DESCRIPTION
This function obtains the default pixel format for the given visual.
.SH RETURN VALUE
Returns a pointer to the \fBggi_pixelformat(3)\fR structure.
.RS
\fBImportant:\fR
Modifying the structure returned is not allowed.  Do \fBnot\fR
attempt to free the pointer returned.
.RE
.SH SEE ALSO
\f(CWggiMapColor(3)\fR, \f(CWggi_pixelformat(3)\fR
