.TH "ggiGetPixelFormat" 3 GGI
.SH NAME
ggiGetPixelFormat \- Get a structure describing the format of a pixelvalue from a visual
.SH SYNOPSIS
\fB#include <ggi/ggi.h>\fR

ggi_pixelformat *\fBggiGetPixelFormat\fR( ggi_visual_t \fIvis\fR );
.SH DESCRIPTION
This function obtains the default pixel format for the given visual.
.SH RETURN VALUE
Returns a pointer to the \fBggi_pixelformat\fR structure.

Modifying the structure returned is not allowed. Do not attempt to free the pointer returned.
.SH STRUCTURES
See \fBggi/ggi.h\fR or \fBggi_pixelformat\fR (3) for details on the structure that is returned.
.SH SEE ALSO
\fBggi_pixelformat\fR (3), \fBggiMapColor\fR (3) 
