.TH "ggiGetPixelFormat" 3 GGI
.SH NAME
\fBggiGetPixelFormat\fR : Get a structure describing the format of a pixelvalue from a visual
.SH SYNOPSIS
.nb
#include <ggi/ggi.h>

const ggi_pixelformat *ggiGetPixelFormat(ggi_visual_t vis);
.fi
.SH DESCRIPTION
This function obtains the default pixel format for the given visual.
.SH RETURN VALUE
Returns a pointer to the \fBggi_pixelformat\fR structure.
BImprotant:R
Modifying the structure returned is not allowed.  Do \*fBnot*\fR
attempt to free the pointer returned.
.SH SEE ALSO
\fBggi_pixelformat(3)\fR, \fBggiMapColor(3)\fR
