.TH "ggiGetInput" 3 "2005-04-17" "libggi-current" GGI
.SH NAME
\fBggiGetInput\fR, \fBggiDetachInput\fR : Functions to translate from GGI visuals to GII input
.SH SYNOPSIS
.nb
.nf
#include <ggi/ggi.h>

#define ggiGetInput(vis) ggiJoinInputs(vis, NULL)

gii_input_t ggiDetachInput(ggi_visual_t vis);
.fi

.SH DESCRIPTION
\fBggiGetInput\fR returns the underlying input-handle associated with a
LibGGI visual, for use with the LibGII API.

\fBggiDetachInput\fR also returns the underlying input-handle, but in
addition, it breaks the association between the given visual and that
input handle.  After this has been done, no LibGGI event routines may
be called on that visual handle, and when the visual handle is closed,
the input will remain unaffected.
.SH SEE ALSO
\f(CWggiJoinInputs(3)\fR, \f(CWgiiOpen(3)\fR
