.TH "ggiGetc" 3 "2005-04-05" "libggi-current" GGI
.SH NAME
\fBggiGetc\fR, \fBggiKbhit\fR : Convenience functions for simplistic keyboard input
.SH SYNOPSIS
.nb
.nf
#include <ggi/ggi.h>

int ggiGetc(ggi_visual_t vis);

int ggiKbhit(ggi_visual_t vis);
.fi

.SH DESCRIPTION
\fBggiGetc\fR gets a character from the keyboard, and blocks if there is
no key immediately available.

\fBggiKbhit\fR checks if a key has been hit on the keyboard.  This does
not consume the key.  It is used for easy porting of old DOS
applications.
.RS
\fBImportant:\fR
\fIDo not\fR poll like this:
\f(CWdo while( ! ggiKbhit(vis) );\fR
On a multitasking OS you would be wasting a lot of resources
which could be available to other processes.  If you want to
wait for a key, use the \fBggiGetc\fR call.
.RE
.SH RETURN VALUE
\fBggiKbhit\fR returns \fB0\fR if no key has been received yet, otherwise
there is a key to be consumed.

\fBggiGetc\fR returns a Unicode character in canonical form.

For a more detailed definition of characters, see \f(CWgii_key_event(3)\fR.
.SH SEE ALSO
\f(CWggiEventPoll(3)\fR
