.TH "ggiGetc" 3 GGI
.SH NAME
ggiGetc, ggiKbhit \- Convenience functions for simplistic keyboard input
.SH SYNOPSIS
\fB#include <ggi/ggi.h>\fR

int ggiGetc ggi_visual_t \fIvis\fR );

int \fBggiKbhit\fR( ggi_visual_t \fIvis\fR );
.SH DESCRIPTION
\fBggiGetc\fR gets a character from the keyboard, and blocks if there is no key immediately available.

\fBggiKbhit\fR checks if a key has been hit on the keyboard. This does not consume the key. It is used for easy porting of old DOS applications.
Do not poll like this: do while( ! ggiKbhit(vis) ); On a multitasking OS you would be wasting a lot of resources which could be available to other processes. If you want to wait for a key, use the \fBggiGetc\fR call.

.SH RETURN VALUE
\fBggiKbhit\fR returns \fB0\fR if no key has been received yet, otherwise there is a key to be consumed.

\fBggiGetc\fR returns a Unicode character in canonical form.

For a fuller definition of characters, see \fBgii_key_event\fR (3).
.SH SEE ALSO
\fBggiJoinInputs\fR (3) 
