.TH "ggiParseMode" 3 GGI
.SH NAME
ggiParseMode, ggiPrintMode, ggiSPrintMode, ggiFPrintMode \- Parse and print formatted strings specifying LibGGI modes
.SH SYNOPSIS
\fB#include <ggi/ggi.h>\fR

int \fBggiParseMode\fR( const char *\fIs\fR,  ggi_mode *\fIm\fR );

int \fBggiPrintMode\fR( ggi_mode *\fIm\fR );

int \fBggiSPrintMode\fR( char *\fIs\fR,  ggi_mode *\fIm\fR );

int \fBggiFPrintMode\fR( FILE *\fIs\fR,  ggi_mode *\fIm\fR );
.SH DESCRIPTION
\fBggiParseMode\fR parses a string into a \fBggi_mode\fR.

The \fBggi*PrintMode\fR functions print all the members of \fBggi_mode\fR in a human-readable form. \fBggiSPrintMode\fR outputs to a preallocated string buffer, \fBggiFPrintMode\fR outputs to a stdio FILE, and \fBggiPrintMode\fR outputs to standard output.  These functions correspond to \fBsprintf \fR (3), \fBfprintf \fR (3), \fBprintf \fR (3), respectively.

The format of the string used by these functions is exactly the same as the one used in the  environment variable.
.SH RETURN VALUE
\fBggiParseMode\fR returns:
.TP
\fB0\fR
on success, i.e. the string was correct. However, errors involving \fBGT_*\fR, position information, or mismatched brackets do not make it fail; these errors are simply ignored.
.PP
.TP
\fB<0\fR
if there is text that can not be parsed. This text is printed to stderr. All parameters parsed so far are written into \fIm\fR.
.PP

So \fIm\fR contains all parameters that have been successfully parsed. For most applications there will be no need for testing \fBggiParseMode\fR for failure.

