.TH "ggiSetColorfulPalette" 3 "2004-11-25" "libggi-current" GGI
.SH NAME
\fBggiSetColorfulPalette\fR : Set a palette with a full range of all colors
.SH SYNOPSIS
.nb
.nf
#include <ggi/ggi.h>

int ggiSetColorfulPalette(ggi_visual_t vis);
.fi

.SH DESCRIPTION
LibGGI guarantees that there will be a default palette when a
palettized mode is set.  What this default is, however, dependent
on the visual.  For example, the X target deliberately avoids setting
all colors to avoid color-flashing when moving between windows.

Applications that want to ensure that they have a full scale of all
colors can call \fBggiSetColorfulPalette\fR after mode set.  This function
uses a smarter color allocation scheme, causing good colors but still
minimal flashing in windowed targets.
.SH RETURN VALUE
\fBggiSetColorfulPalette\fR returns the number of the first entry changed.
\fB<0\fR indicate an \fBggi-error(3)\fR.
.SH SEE ALSO
\fBggiSetPalette(3)\fR
