.TH "ggiSetGCForeground" 3 "2003-04-02 06:39:16" "ggi-current" GGI
.SH NAME
\fBggiSetGCForeground\fR, \fBggiGetGCForeground\fR, \fBggiSetGCBackground\fR, \fBggiGetGCBackground\fR : Set or get the foreground or background color used in drawing operations in a visual
.SH SYNOPSIS
.nb
.nf
#include <ggi/ggi.h>

int ggiSetGCForeground(ggi_visual_t vis,ggi_pixel  color);

int ggiGetGCForeground(ggi_visual_t vis,ggi_pixel *color);

int ggiSetGCBackground(ggi_visual_t vis,ggi_pixel  color);

int ggiGetGCBackground(ggi_visual_t vis,ggi_pixel *color);
.fi

.SH DESCRIPTION
\fBggiSetGCForeground\fR and \fBggiGetGCForeground\fR set or reads the current
colors for the foreground, used in all normal drawing functions.

\fBggiSetGCBackground\fR and \fBggiGetGCBackground\fR set or reads the current
colors for the background, used in two-color operations like drawing
text.
.SH RETURN VALUE
All four functions \fB0\fR for OK.
