.TH "ggiSetColorfulPalette" 3 GGI
.SH NAME
ggiSetColorfulPalette \- Set a palette with a full range of all colors
.SH SYNOPSIS
\fB#include <ggi/ggi.h>\fR

int \fBggiSetColorfulPalette\fR( ggi_visual_t \fIvis\fR );
.SH DESCRIPTION
LibGGI guarantees that there will be a default palette when a palettized mode is set.  What this default is, however, is dependent on the visual.  For example, the X target deliberately avoids setting all colors to avoid color-flashing when moving between windows.

Applicaations that want to ensure that they have a full scale of all colors can call \fBggiSetColorfulPalette\fR after mode set.  This function uses a smarter color allocation scheme, causing good colors but still minimal flashing in windowed targets.
.SH RETURN VALUE
\fBggiSetColorfulPalette\fR returns the number of the first entry changed.  Negative values indicate error (codes).
.SH SEE ALSO
\fBggiSetPalette\fR (3)  
