.TH "ggiSetGCForeground" 3 GGI
.SH NAME
ggiSetGCForeground, ggiGetGCForeground, ggiSetGCBackground, ggiGetGCBackground \- Set or get the foreground or background color used in drawing operations in a visual
.SH SYNOPSIS
\fB#include <ggi/ggi.h>\fR

int \fBggiSetGCForeground\fR( ggi_visual_t \fIvis\fR,  ggi_pixel \fIcolor\fR );

int \fBggiGetGCForeground\fR( ggi_visual_t \fIvis\fR,  ggi_pixel *\fIcolor\fR );

int \fBggiSetGCBackground\fR( ggi_visual_t \fIvis\fR,  ggi_pixel \fIcolor\fR );

int \fBggiGetGCBackground\fR( ggi_visual_t \fIvis\fR,  ggi_pixel *\fIcolor\fR );
.SH DESCRIPTION
\fBggiSetGCForeground\fR and \fBggiGetGCForeground\fR set or reads the current colors for the foreground, used in all normal drawing functions.

\fBggiSetGCBackground\fR and \fBggiGetGCBackground\fR set or reads the current colors for the background, used in two-color operations like drawing text.
.SH RETURN VALUE
All four functions \fB0\fR for OK.

