.TH "triple-int" 7 "2004-10-26" "libggi-current" GGI
.SH NAME
\fBtriple-int\fR : triple-int General Information
.SH SYNOPSIS
.nb
.nf
#include <ggi/internal/triple-int.h>
.fi

.SH DESCRIPTION
\fBtriple-int\fR is a collection of math routines that operates on an
array of 3 unsigned intergers, treating them as a single integer
with triple precision.

\fBtriple-int\fR uses a 2-complement representation for negative values.

The most significant part of the \fBtriple-int\fR is stored at the
highest index in the array representation.

A \fBtriple-int\fR is typically declared as follows:

.nb
.nf
unsigned x[3];
.fi

Don't let the above unsigned keyword fool you, all the routines
operate as if the \fBtriple-int\fR is signed.
.SH SEE ALSO
\f(CWassign_3(3)\fR, \f(CWassign_int_3(3)\fR, \f(CWassign_unsigned_3(3)\fR,
\f(CWsign_3(3)\fR, \f(CWbits_3(3)\fR, \f(CWeq0_3(3)\fR, \f(CWgt0_3(3)\fR,
\f(CWge0_3(3)\fR, \f(CWlt0_3(3)\fR, \f(CWle0_3(3)\fR,
\f(CWeq_3(3)\fR, \f(CWge_3(3)\fR,
\f(CWinvert_3(3)\fR, \f(CWlshift_3(3)\fR, \f(CWrshift_3(3)\fR,
\f(CWinc_3(3)\fR, \f(CWdec_3(3)\fR, \f(CWnegate_3(3)\fR, \f(CWabs_3(3)\fR,
\f(CWadd_3(3)\fR, \f(CWsub_3(3)\fR, \f(CWmul_3(3)\fR, \f(CWdivmod_3(3)\fR
